openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: stockController
  description: 주식 조회 API
paths:
  /stocks:
    get:
      tags:
      - stockController
      description: 주식 조회
      operationId: fetchApiAndSave
      parameters:
      - name: symbol
        in: query
        description: 주식의 상장 코드
        required: true
        example: 005930.KS
      - name: interval
        in: query
        description: 주식 데이터 조회 단위
        example: 1d
      - name: range
        in: query
        description: 주식 데이터 조회 범위
        required: true
        example: 5d
      - name: requestParamDto
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/RequestParamDto'
      responses:
        "200":
          description: 성공
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseDtoListStockResponseDto'
        "400":
          description: Invalid param
          content:
            '*/*':
              example:
                code: BAD_REQUEST
                detail: "222d is invalid, 1d, 5d, 1mo, 3mo, 6mo, 1y, 2y, 5y, 10y,\
                  \ ytd, max"
                data: null
        "500":
          description: Server Error
          content:
            '*/*':
              example:
                code: ERROR
                detail: Server Error
                data: null
components:
  schemas:
    RequestParamDto:
      type: object
      properties:
        symbol:
          type: string
        interval:
          type: string
        range:
          type: string
    ApiResponseDtoListStockResponseDto:
      type: object
      properties:
        code:
          type: string
          enum:
          - SUCCESS
          - ERROR
          - INVALID_STOCK_SIZE
          - BAD_REQUEST
        detail:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/StockResponseDto'
    StockResponseDto:
      type: object
      properties:
        date:
          type: string
          format: date
        name:
          type: string
        high:
          type: integer
          format: int64
        low:
          type: integer
          format: int64
        open:
          type: integer
          format: int64
        close:
          type: integer
          format: int64
        volume:
          type: integer
          format: int64
